#!/bin/sh

# Copyright (C) Alejandro Acosta 2006 
# Distributed under GPL License. See COPYING.

# createVersionH.sh
# AA 2006/05/23
# MODIFIED 2006/12/16
# 1. generate Version.h (used by main.cpp to include build info)

VERSIONDOTH=../../include/Version.h

VERSION=$1
NAME=$2

TIMESTAMP=$(date)

if test -e $VERSIONDOTH
then
    mv $VERSIONDOTH $VERSIONDOTH~
fi

echo "/* Header generated by createVersionH.sh */" > $VERSIONDOTH 
echo >> $VERSIONDOTH 
echo "#ifndef _VERSION_H_" >> $VERSIONDOTH 
echo "#define _VERSION_H_" >> $VERSIONDOTH 
echo >> $VERSIONDOTH
echo "#define _INSTALLED_NAME_ \"$NAME\"" >> $VERSIONDOTH 
echo "#define _VERSION_ \"$VERSION\"" >> $VERSIONDOTH 
echo "#define _BUILT_ \"$TIMESTAMP\"" >> $VERSIONDOTH 
echo "#define _MACHINE_ \"$MACHTYPE\"" >> $VERSIONDOTH 
echo "#define _BUILDER_ \"$USER\"" >> $VERSIONDOTH 
echo >> $VERSIONDOTH
echo "#endif // _VERSION_H_" >> $VERSIONDOTH 
echo >> $VERSIONDOTH

echo "  Generated 'Version.h'" >&1