/* Header generated by createVersionH.sh */

#ifndef _VERSION_H_
#define _VERSION_H_

#define _INSTALLED_NAME_ "maca_segmenter"
#define _VERSION_ "2.5"
#define _BUILT_ "Wed Oct 24 13:00:36 PDT 2007"
#define _MACHINE_ "powerpc-apple-darwin8.0"
#define _BUILDER_ "araleius"

#endif // _VERSION_H_

